/**
 * Third-party runtime dependencies and their declared licences.
 *
 * GENERATED from the root `package.json` + the installed `node_modules` manifests.
 * Regenerate whenever dependencies change; do not hand-edit individual rows.
 *
 * This list covers direct runtime dependencies. Transitive dependencies carry
 * their own notices inside their packages in `node_modules`.
 */
export interface DependencyLicense {
  readonly name: string;
  readonly version: string;
  readonly license: string;
}

export const dependencyLicenses: readonly DependencyLicense[] = [
  { name: "@ag-ui/mastra", version: "1.0.1", license: "Apache-2.0" },
  { name: "@ai-sdk/openai", version: "2.0.98", license: "Apache-2.0" },
  { name: "@atproto/api", version: "0.15.27", license: "MIT" },
  { name: "@aws-sdk/client-s3", version: "3.1003.0", license: "Apache-2.0" },
  { name: "@aws-sdk/s3-request-presigner", version: "3.1003.0", license: "Apache-2.0" },
  { name: "@casl/ability", version: "6.8.0", license: "MIT" },
  { name: "@copilotkit/react-core", version: "1.10.6", license: "MIT" },
  { name: "@copilotkit/react-textarea", version: "1.10.6", license: "MIT" },
  { name: "@copilotkit/react-ui", version: "1.10.6", license: "MIT" },
  { name: "@copilotkit/runtime", version: "1.10.6", license: "MIT" },
  { name: "@dub/analytics", version: "0.0.32", license: "MPL-2.0" },
  { name: "@hookform/resolvers", version: "3.10.0", license: "MIT" },
  { name: "@langchain/community", version: "1.1.27", license: "MIT" },
  { name: "@langchain/core", version: "1.1.39", license: "MIT" },
  { name: "@langchain/langgraph", version: "1.2.8", license: "MIT" },
  { name: "@langchain/openai", version: "1.4.3", license: "MIT" },
  { name: "@langchain/tavily", version: "1.2.0", license: "MIT" },
  { name: "@mantine/core", version: "5.10.5", license: "MIT" },
  { name: "@mantine/dates", version: "5.10.5", license: "MIT" },
  { name: "@mantine/hooks", version: "5.10.5", license: "MIT" },
  { name: "@mantine/modals", version: "5.10.5", license: "MIT" },
  { name: "@mastra/core", version: "1.21.0", license: "Apache-2.0" },
  { name: "@mastra/mcp", version: "1.4.1", license: "Apache-2.0" },
  { name: "@mastra/memory", version: "1.13.0", license: "Apache-2.0" },
  { name: "@mastra/pg", version: "1.8.5", license: "Apache-2.0" },
  { name: "@meronex/icons", version: "4.0.0", license: "MIT" },
  { name: "@modelcontextprotocol/sdk", version: "1.27.1", license: "MIT" },
  { name: "@nest-lab/throttler-storage-redis", version: "1.2.0", license: "MIT" },
  { name: "@nestjs/cli", version: "11.0.21", license: "MIT" },
  { name: "@nestjs/common", version: "11.1.21", license: "MIT" },
  { name: "@nestjs/core", version: "11.1.21", license: "MIT" },
  { name: "@nestjs/microservices", version: "11.1.21", license: "MIT" },
  { name: "@nestjs/platform-express", version: "11.1.21", license: "MIT" },
  { name: "@nestjs/schedule", version: "6.1.3", license: "MIT" },
  { name: "@nestjs/swagger", version: "11.4.3", license: "MIT" },
  { name: "@nestjs/throttler", version: "6.5.0", license: "MIT" },
  { name: "@neynar/nodejs-sdk", version: "3.137.0", license: "MIT" },
  { name: "@neynar/react", version: "1.2.22", license: "MIT" },
  { name: "@pigment-css/react", version: "0.0.30", license: "MIT" },
  { name: "@postiz/wallets", version: "0.0.1", license: "Apache-2.0" },
  { name: "@prisma/client", version: "6.5.0", license: "Apache-2.0" },
  { name: "@sentry/nestjs", version: "10.45.0", license: "MIT" },
  { name: "@sentry/nextjs", version: "10.45.0", license: "MIT" },
  { name: "@sentry/profiling-node", version: "10.45.0", license: "MIT" },
  { name: "@sentry/react", version: "10.45.0", license: "MIT" },
  { name: "@solana/wallet-adapter-react", version: "0.15.39", license: "Apache-2.0" },
  { name: "@solana/wallet-adapter-react-ui", version: "0.9.39", license: "Apache-2.0" },
  { name: "@stripe/react-stripe-js", version: "5.6.1", license: "MIT" },
  { name: "@stripe/stripe-js", version: "8.9.0", license: "MIT" },
  { name: "@swc/helpers", version: "0.5.13", license: "Apache-2.0" },
  { name: "@sweetalert2/theme-dark", version: "5.0.27", license: "MIT" },
  { name: "@tailwindcss/postcss", version: "4.2.1", license: "MIT" },
  { name: "@temporalio/activity", version: "1.15.0", license: "MIT" },
  { name: "@temporalio/client", version: "1.15.0", license: "MIT" },
  { name: "@temporalio/common", version: "1.15.0", license: "MIT" },
  { name: "@temporalio/worker", version: "1.15.0", license: "MIT" },
  { name: "@temporalio/workflow", version: "1.15.0", license: "MIT" },
  { name: "@tiptap/extension-bold", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/extension-document", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/extension-heading", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/extension-history", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/extension-link", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/extension-list", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/extension-mention", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/extension-paragraph", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/extension-text", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/extension-underline", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/pm", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/react", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/starter-kit", version: "3.20.1", license: "MIT" },
  { name: "@tiptap/suggestion", version: "3.20.1", license: "MIT" },
  { name: "@types/bcrypt", version: "5.0.2", license: "MIT" },
  { name: "@types/concat-stream", version: "2.0.3", license: "MIT" },
  { name: "@types/facebook-nodejs-business-sdk", version: "20.0.3", license: "MIT" },
  { name: "@types/jsonwebtoken", version: "9.0.10", license: "MIT" },
  { name: "@types/lodash", version: "4.17.24", license: "MIT" },
  { name: "@types/md5", version: "2.3.6", license: "MIT" },
  { name: "@types/mime", version: "3.0.4", license: "MIT" },
  { name: "@types/mime-types", version: "2.1.4", license: "MIT" },
  { name: "@types/multer", version: "1.4.13", license: "MIT" },
  { name: "@types/nodemailer", version: "6.4.23", license: "MIT" },
  { name: "@types/parse5", version: "6.0.1", license: "MIT" },
  { name: "@types/react-dropzone", version: "4.2.2", license: "MIT" },
  { name: "@types/remove-markdown", version: "0.3.4", license: "MIT" },
  { name: "@types/sha256", version: "0.2.2", license: "MIT" },
  { name: "@types/striptags", version: "0.0.5", license: "MIT" },
  { name: "@types/yup", version: "0.32.0", license: "MIT" },
  { name: "@uidotdev/usehooks", version: "2.4.1", license: "MIT" },
  { name: "@uiw/react-md-editor", version: "4.0.11", license: "MIT" },
  { name: "@uppy/aws-s3", version: "4.3.2", license: "MIT" },
  { name: "@uppy/compressor", version: "2.3.2", license: "MIT" },
  { name: "@uppy/core", version: "4.5.3", license: "MIT" },
  { name: "@uppy/dashboard", version: "4.4.3", license: "MIT" },
  { name: "@uppy/drag-drop", version: "4.2.2", license: "MIT" },
  { name: "@uppy/file-input", version: "4.2.2", license: "MIT" },
  { name: "@uppy/progress-bar", version: "4.3.2", license: "MIT" },
  { name: "@uppy/react", version: "4.5.2", license: "MIT" },
  { name: "@uppy/status-bar", version: "4.2.3", license: "MIT" },
  { name: "@uppy/transloadit", version: "4.3.3", license: "MIT" },
  { name: "@uppy/xhr-upload", version: "4.4.2", license: "MIT" },
  { name: "accept-language", version: "3.0.20", license: "MIT" },
  { name: "array-move", version: "4.0.0", license: "MIT" },
  { name: "async-mutex", version: "0.5.0", license: "MIT" },
  { name: "axios", version: "1.14.0", license: "MIT" },
  { name: "bcrypt", version: "5.1.1", license: "MIT" },
  { name: "bottleneck", version: "2.19.5", license: "MIT" },
  { name: "bs58", version: "6.0.0", license: "MIT" },
  { name: "bufferutil", version: "4.1.0", license: "MIT" },
  { name: "canvas", version: "2.11.2", license: "MIT" },
  { name: "chart.js", version: "4.5.1", license: "MIT" },
  { name: "class-transformer", version: "0.5.1", license: "MIT" },
  { name: "class-validator", version: "0.14.4", license: "MIT" },
  { name: "class-validator-jsonschema", version: "5.1.0", license: "MIT" },
  { name: "clsx", version: "2.1.1", license: "MIT" },
  { name: "compression", version: "1.8.1", license: "MIT" },
  { name: "concat-stream", version: "2.0.0", license: "MIT" },
  { name: "cookie-parser", version: "1.4.7", license: "MIT" },
  { name: "copy-to-clipboard", version: "3.3.3", license: "MIT" },
  { name: "crypto-hash", version: "3.1.0", license: "MIT" },
  { name: "dayjs", version: "1.11.19", license: "MIT" },
  { name: "dotenv", version: "16.6.1", license: "BSD-2-Clause" },
  { name: "dotenv-cli", version: "8.0.0", license: "MIT" },
  { name: "emoji-picker-react", version: "4.18.0", license: "MIT" },
  { name: "evp_bytestokey", version: "1.0.3", license: "MIT" },
  { name: "facebook-nodejs-business-sdk", version: "21.0.5", license: "Platform License" },
  { name: "fast-xml-parser", version: "4.5.4", license: "MIT" },
  { name: "file-type", version: "16.5.4", license: "MIT" },
  { name: "google-auth-library", version: "9.15.1", license: "Apache-2.0" },
  { name: "googleapis", version: "137.1.0", license: "Apache-2.0" },
  { name: "hot-reload-extension-vite", version: "1.1.0", license: "MIT" },
  { name: "i18n-iso-countries", version: "7.14.0", license: "MIT" },
  { name: "i18next", version: "25.8.14", license: "MIT" },
  { name: "i18next-browser-languagedetector", version: "8.2.1", license: "MIT" },
  { name: "i18next-resources-to-backend", version: "1.2.1", license: "MIT" },
  { name: "image-to-pdf", version: "3.0.2", license: "ISC" },
  { name: "ioredis", version: "5.10.0", license: "MIT" },
  { name: "isomorphic-dompurify", version: "3.10.0", license: "MIT" },
  { name: "json-to-graphql-query", version: "2.3.0", license: "MIT" },
  { name: "jsonwebtoken", version: "9.0.3", license: "MIT" },
  { name: "lodash", version: "4.17.23", license: "MIT" },
  { name: "mastra", version: "1.3.19", license: "Apache-2.0" },
  { name: "md5", version: "2.3.0", license: "BSD-3-Clause" },
  { name: "mime", version: "3.0.0", license: "MIT" },
  { name: "mime-types", version: "2.1.35", license: "MIT" },
  { name: "multer", version: "1.4.5-lts.2", license: "MIT" },
  { name: "music-metadata", version: "7.14.0", license: "MIT" },
  { name: "nestjs-command", version: "3.1.5", license: "MIT" },
  { name: "nestjs-real-ip", version: "3.0.1", license: "MIT" },
  { name: "nestjs-temporal-core", version: "3.2.3", license: "MIT" },
  { name: "next", version: "16.2.6", license: "MIT" },
  { name: "next-plausible", version: "3.12.5", license: "MIT" },
  { name: "node-fetch", version: "3.3.2", license: "MIT" },
  { name: "node-telegram-bot-api", version: "0.66.0", license: "MIT" },
  { name: "nodemailer", version: "7.0.13", license: "MIT-0" },
  { name: "nostr-tools", version: "2.23.3", license: "Unlicense" },
  { name: "openai", version: "6.27.0", license: "Apache-2.0" },
  { name: "p-limit", version: "3.1.0", license: "MIT" },
  { name: "parse5", version: "6.0.1", license: "MIT" },
  { name: "polotno", version: "3.0.0-beta.25", license: "SEE LICENSE IN LICENSE.md" },
  { name: "posthog-js", version: "1.359.1", license: "SEE LICENSE IN LICENSE" },
  { name: "react", version: "19.2.4", license: "MIT" },
  { name: "react-colorful", version: "5.6.1", license: "MIT" },
  { name: "react-country-flag", version: "3.1.0", license: "MIT" },
  { name: "react-dnd", version: "16.0.1", license: "MIT" },
  { name: "react-dnd-html5-backend", version: "16.0.1", license: "MIT" },
  { name: "react-dom", version: "19.2.4", license: "MIT" },
  { name: "react-dropzone", version: "14.4.1", license: "MIT" },
  { name: "react-hook-form", version: "7.71.2", license: "MIT" },
  { name: "react-hotkeys-hook", version: "5.2.4", license: "MIT" },
  { name: "react-i18next", version: "15.7.4", license: "MIT" },
  { name: "react-loading", version: "2.0.3", license: "MIT" },
  { name: "react-sortablejs", version: "6.1.4", license: "MIT" },
  { name: "react-tag-autocomplete", version: "7.5.1", license: "ISC" },
  { name: "react-tooltip", version: "5.30.0", license: "MIT" },
  { name: "react-use-cookie", version: "1.6.1", license: "MIT" },
  { name: "react-use-keypress", version: "1.4.0", license: "MIT" },
  { name: "redis", version: "4.7.1", license: "MIT" },
  { name: "reflect-metadata", version: "0.2.2", license: "Apache-2.0" },
  { name: "remove-markdown", version: "0.5.5", license: "MIT" },
  { name: "resend", version: "3.5.0", license: "MIT" },
  { name: "rss-parser", version: "3.13.0", license: "MIT" },
  { name: "rxjs", version: "7.8.2", license: "Apache-2.0" },
  { name: "sass", version: "1.97.3", license: "MIT" },
  { name: "sha256", version: "0.2.0", license: "UNKNOWN" },
  { name: "sharp", version: "0.33.5", license: "Apache-2.0" },
  { name: "simple-statistics", version: "7.8.8", license: "ISC" },
  { name: "slugify", version: "1.6.6", license: "MIT" },
  { name: "stripe", version: "20.4.0", license: "MIT" },
  { name: "striptags", version: "3.2.0", license: "MIT" },
  { name: "subtitle", version: "4.2.2-alpha.0", license: "MIT" },
  { name: "sweetalert2", version: "11.4.8", license: "MIT" },
  { name: "swr", version: "2.4.1", license: "MIT" },
  { name: "tailwind-scrollbar", version: "3.1.0", license: "MIT" },
  { name: "tailwindcss", version: "3.4.17", license: "MIT" },
  { name: "tailwindcss-rtl", version: "0.9.0", license: "MIT" },
  { name: "timezones-list", version: "3.1.0", license: "MIT" },
  { name: "tippy.js", version: "6.3.7", license: "MIT" },
  { name: "tldts", version: "6.1.86", license: "MIT" },
  { name: "transloadit", version: "3.0.2", license: "MIT" },
  { name: "tslib", version: "2.8.1", license: "0BSD" },
  { name: "tweetnacl", version: "1.0.3", license: "Unlicense" },
  { name: "twitter-api-v2", version: "1.29.0", license: "Apache-2.0" },
  { name: "twitter-text", version: "3.1.0", license: "UNKNOWN" },
  { name: "use-debounce", version: "10.1.0", license: "MIT" },
  { name: "utf-8-validate", version: "5.0.10", license: "MIT" },
  { name: "uuid", version: "10.0.0", license: "MIT" },
  { name: "viem", version: "2.47.0", license: "MIT" },
  { name: "webextension-polyfill", version: "0.12.0", license: "MPL-2.0" },
  { name: "ws", version: "8.19.0", license: "MIT" },
  { name: "yargs", version: "17.7.2", license: "MIT" },
  { name: "yup", version: "1.7.1", license: "MIT" },
  { name: "zod", version: "3.25.76", license: "MIT" },
  { name: "zustand", version: "5.0.11", license: "MIT" },
];

/** Count of direct dependencies per declared licence, most common first. */
export const licenseSummary: readonly { readonly license: string; readonly count: number }[] = [
  { license: "MIT", count: 176 },
  { license: "Apache-2.0", count: 21 },
  { license: "ISC", count: 3 },
  { license: "MPL-2.0", count: 2 },
  { license: "Unlicense", count: 2 },
  { license: "UNKNOWN", count: 2 },
  { license: "BSD-2-Clause", count: 1 },
  { license: "Platform License", count: 1 },
  { license: "BSD-3-Clause", count: 1 },
  { license: "MIT-0", count: 1 },
  { license: "SEE LICENSE IN LICENSE.md", count: 1 },
  { license: "SEE LICENSE IN LICENSE", count: 1 },
  { license: "0BSD", count: 1 },
];
