import Link from 'next/link';
import { pages } from '../content/pages';
import { CopySnippet } from './copy-snippet';

export function AgentLanding({ slug }: {slug:string}) {
  const page=pages[slug];
  const client=slug==='claude-cowork'?'Claude Cowork':slug==='codex'?'Codex':'your AI assistant';
  const code=slug==='codex' ? '[mcp_servers.postdelegate]\nurl = "https://YOUR-WORKSPACE-HOST/api/v1/mcp"\nbearer_token_env_var = "POSTDELEGATE_API_KEY"' : 'https://YOUR-WORKSPACE-HOST/api/v1/mcp';
  return <article className="agent-landing">
    <header className="agent-hero"><div className="agent-client-badge">POSTDELEGATE × {client.toUpperCase()}</div><h1>Social media publishing<br/>for {client}.</h1><p>Create drafts, work with media and schedule posts through MCP. Keep your channels, calendar and approvals together in PostDelegate.</p><div className="agent-hero-actions"><a href="#connect-agent">See how to connect <span aria-hidden="true">↓</span></a><Link href="/api">API documentation ↗</Link></div><small>Public preview · Hosted connections are not open yet. <Link href="/status">Launch status</Link></small></header>
    <section className="agent-start" id="connect-agent"><span className="agent-kicker">START WITH A CONNECTION</span><h2>Bring your agent into the workflow.</h2><p>{slug==='codex'?'Add the configuration to your Codex environment and supply the key securely.':'Add your workspace’s MCP URL to a compatible remote connector, then authorize access.'} Follow the setup guide below for permissions and prerequisites.</p><div id="public-tool" data-tool-kind="copy" data-code={code}><CopySnippet code={code}/></div></section>
    <section className="agent-benefits"><div><span>01 / DRAFT</span><h3>Turn a brief into a saved post.</h3><p>Send content from your agent to the workspace. Review it before choosing when it goes live.</p></div><div><span>02 / SCHEDULE</span><h3>Plan the next week of content.</h3><p>Schedule prepared posts and check each channel’s result from the same workflow.</p></div><div><span>03 / OVERSEE</span><h3>Keep the final say.</h3><p>Choose which accounts your agent can use and keep required approvals in place.</p></div></section>
    <section className="agent-workflow"><div><span className="agent-kicker">WHAT TO ASK</span><h2>Start with a real publishing task.</h2><p>Your AI client prepares the content. PostDelegate handles the draft and scheduling workflow.</p></div><div className="agent-prompt"><span>EXAMPLE REQUEST</span><blockquote>“Create a draft from my launch notes. Use the LinkedIn account I choose and leave the post ready for review.”</blockquote><div><code>list_accounts</code><span>→</span><code>create_draft</code><span>→</span><code>get_post</code></div><small>Example workflow, not a recorded publishing result.</small></div></section>
    <section className="agent-guide-details"><span className="agent-kicker">SETUP GUIDE</span><h2>Connect {client}, step by step.</h2>{page.sections.map((section,i)=><details key={section.heading} open={i===1}><summary><span>{String(i+1).padStart(2,'0')}</span>{section.heading}</summary><p>{section.body}</p>{section.items&&<ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul>}{section.code&&<pre><code>{section.code}</code></pre>}</details>)}</section>
    <section className="agent-bottom"><h2>Your agent does the legwork.<br/>Your workspace keeps it organized.</h2><p>Explore the app, review the connection steps and start with a draft.</p><Link href="/status">View launch status ↗</Link><Link href="/agents">More agent guides →</Link></section>
  </article>;
}
